//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RotoScope.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_RotoScopeTYPE               129
#define ID_MOVIES_OPENSOURCEMOVIE       32771
#define ID_MOVIES_OPENOUTPUTMOVIE       32772
#define ID_MOVIES_CLOSEOUTPUTMOVIE      32773
#define ID_FRAMES_READONEFRAME          32774
#define ID_FRAMES_CREATEONEFRAME        32775
#define ID_FRAMES_WRITEONEFRAME         32777
#define ID_MOVIES_CLOSESOURCEMOVIE      32778
#define ID_FRAMES_WRITETHENCREATEONEFRAME 32779
#define ID_FRAMES_WRITETHENCREATEONESECOND 32781
#define ID_FRAMES_WRITETHENCREATEREMAINING 32782
#define ID_MOVIES_OPENBACKGROUNDAUDIO   32783
#define ID_MOVIES_CLOSEBACKGROUNDAUDIO  32784
#define ID_EDIT_CLEARFRAME              32785
#define ID_EDIT_SABERMODE               32786
#define ID_EDIT_ROTATIONMODE            32787
#define ID_EDIT_BIRDMODE                32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
